priorities=[?a..?z, ?A..?Z] |> Enum.concat() |> Enum.with_index(1) |> Map.new()
File.read!("input")
 |> String.split("\n")
 |> Enum.map(& String.to_charlist(&1) |> MapSet.new())
 |> Enum.chunk_every(3)
 |> Enum.flat_map(fn g -> Enum.reduce(g, &MapSet.intersection/2) end)
 |> Enum.map(&priorities[&1])
 |> Enum.sum()
 |> IO.inspect()
